apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: testcloud
build:
  artifacts:
    - image: testcloud
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kube/deployment.yaml
    - kube/secret.yaml
    - kube/service.yaml
    - kube/ingress.yaml
